enum Provider {
	GOOGLE
	# TWITTER
	# FACEBOOK
	# GITHUB
}

type AuthResponse {
	user: User!
	newAccount: Boolean! # was it a registration ?
	newSession: Boolean! # was it a non existing session ? usefull to implement security later
}

type AuthType {
	local: Local!
	sso: Sso!
}

interface AuthOps {
	signout: String @Auth
}

input Creds {
	email: String!
	pwd: String!
	rememberMe: Boolean
}

type Local implements AuthOps {
	signin(creds: Creds!): AuthResponse!
	signup(creds: Creds!): AuthResponse!
	signout: String @Auth
}

type Sso implements AuthOps {
	sign(provider: Provider!, idToken: String!): AuthResponse!
	signout: String @Auth # void
}

# I CAN'T RETURN AN INTERFACE TO QUERY MORE, I HAVE TO IMPLEM
# authenticate(type)
type Mutation {
	authenticate: AuthType!
}