directive @auth(canAccessTokenBeExpired: Boolean) on FIELD_DEFINITION
directive @verifyRefreshToken on FIELD_DEFINITION
directive @localOnly on FIELD_DEFINITION

enum Provider {
	GOOGLE
	# TWITTER
	# FACEBOOK
	# GITHUB
}

input Local {
	email: String!
	pwd: String!
	rememberMe: Boolean
}

input SSO {
	provider: Provider!
	idToken: String!
	rememberMe: Boolean
}

type Stage {
	stage: String!
	version: String!
}

type Query {
	# Pong
	ping: String!
	# stage and version
	stage: Stage!
	# Hello user
	whoami: User! @auth
	cert: String!
	# An accessToken is used to access different services
	accessToken: String @auth(canAccessTokenBeExpired: true) @verifyRefreshToken
	gamemodeTwo(email: String!): String! @localOnly
}

type Mutation {
	logout: Boolean!
	refreshToken(creds: Local, sso: SSO, signup: Boolean): String
	createResetCode(email: String!): Boolean!
	resetPassword(email: String!, newPwd: String!, resetCode: String!): Boolean!
	inviteUser(email: String!): String @auth
}
