type Session {
  ip: String!
  browserName: String
  osName: String
  deviceModel: String
  deviceType: String
  deviceVendor: String
}

type User {
  id: ID!
  sessions: [Session!]!
  emailVerified: Boolean!
}