directive @NOFREQS on OBJECT
directive @NOHL on OBJECT
directive @TAG on FIELD_DEFINITION

enum Lang {
  EN
  FR
}

type Query {
  """
  pong
  """
  ping: String!
  """
  The logged user

  Throws:
    - USER_NOT_FOUND: If the user is not found
  """
  me: User!
}

type Mutation {
  """
  Create an user account and send an ACCOUNT_CREATE socket message

  Returns: true
  Throws:
    - REGISTRATION_DISABLED: If the registration is disabled
    - MAIL_INVALID: If the mail doesn't respect the policy
    - PASSWORD_INVALID: If the pwd doesn't respect the policy
    - MAIL_USED: If the mail is already used
  """
  create_user(mail: String!, pwd: String!, lang: Lang): Boolean!

  """
  Create an user account for another person
  and send an ACCOUNT_INVITE socket message

  Returns: Id of the invited user
  Throws:
    - REGISTRATION_DISABLED: If the registration is disabled
    - MAIL_INVALID: If the mail doesn't respect the policy
    - USER_NOT_FOUND: If the user is not found
    - MAIL_USED: If the mail is already used
  """
  invite_user(mail: String!, lang: Lang): ID!

  """
  Creating a session means authenticating an user
  and saving a session hash which can be revoked later

  Returns: true if the session is new, false if it already existed
  Throws:
    - USER_NOT_FOUND: If the user doesn't exist or the password is invalid
    - MAIL_INVALID: If the mail doesn't respect the policy
    - PASSWORD_INVALID: If the pwd doesn't respect the policy
    - NO_PASSWORD: If the user has no password and first need to
      request a reset code to reset his password
    - ILLEGAL_SESSION: If the user agent is invalid
  """
  create_session(
    mail: String!
    pwd: String!
    remember: Boolean = false
    lang: Lang
  ): Boolean!

  """
  Create and fix a fresh access token

  Returns: true
  Throws:
    - USER_NOT_FOUND: If the user is not found
    - ILLEGAL_SESSION: If the session was revoked
  """
  refresh_session: Boolean!

  """
  If the email exist, send a reset code.
  The code is only valid for 24h

  Returns: true
  Throws:
    - SPAM: If the user request too fast another code
  """
  create_pwd_reset_code(mail: String!, lang: Lang): Boolean!

  """
  Resend an account confirmation code

  Returns: true
  Throws:
    - USER_NOT_FOUND: If the user is not found
    - SPAM: If the user request too fast another code
  """
  create_account_confirm_code(lang: Lang): Boolean!

  """
  Update an user's password with a reset code sent by mail

  Returns: true
  Throws:
    - PASSWORD_INVALID: If the pwd doesn't respect the policy
    - USER_NOT_FOUND: If the user is not found
    - INVALID_CODE: If the reset code is invalid or expired
  """
  update_pwd(code: String!, mail: String!, pwd: String!): Boolean!
  """
  Update an user's password while being logged

  Returns: true
  Throws:
    - PASSWORD_INVALID: If the pwd doesn't respect the policy
    - USER_NOT_FOUND: If the user is not found or if the current pass is invalid
  """
  update_pwd_logged(current_pwd: String!, new_pwd: String!): Boolean!
  """
  Confirm the user account

  Returns: true
  Throws:
    - USER_NOT_FOUND: If the user is not found
    - INVALID_CODE: If the verification code is invalid or expired
  """
  confirm_account(code: String!): Boolean!

  """
  Try to delete a session.
  If the ID is provided and the session exist it will be deleted.
  If the ID is not provided it will delete the current session
  If the user is not logged then it just remove session cookies

  Returns: true
  Throws:
    - ILLEGAL_SESSION: If the provided id doesn't exist
  """
  delete_session(id: ID): Boolean!

  """
  Attempt to delete some users

  Returns: true
  Throws:
    - USER_NOT_FOUND: If the user is not found
    - UNAUTHORIZED: If the user is not an admin
  """
  admin_delete_users(ids: [ID!]!): Boolean!

  """
  Update an user's password (requires admin rights)

  Returns: true
  Throws:
    - PASSWORD_INVALID: If the pwd doesn't respect the policy
    - USER_NOT_FOUND: If the user is not found
    - UNAUTHORIZED: If the user is not an admin
  """
  admin_update_pwd(id: ID!, pwd: String!): Boolean!
}

type Session {
  uuid: ID!
  last_used: String
  hash: String!
  ip: String
  browserName: String
  osName: String
  deviceModel: String
  deviceType: String
  deviceVendor: String
}

type User {
  uuid: ID!
  mail: String!
  sessions: [Session!]!
  verified: Boolean!
  member_since: String!
}
