type Session {
  uuid: ID!
  hash: String!
  ip: String!
  browserName: String
  osName: String
  deviceModel: String
  deviceType: String
  deviceVendor: String
}

type User @MAXTEXTFIELDS @NOFREQS {
  uuid: ID!
  mail: String! @TAG
  sessions: [Session!]!
  verified: Boolean!
}